local_backend: true
#Must be put on top
#local_backend: true 
    # when using a custom proxy server port
    #url: http://localhost:8081/api/v1
    # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
    #allowed_hosts: ['192.168.0.1']
backend:
  name: git-gateway
  branch: main


media_folder: static/images
public_folder: /images
collections:
  - name: config
    label: Global Site Config
    files:
      - name: config
        label: Global Site Config
        file: config.yaml
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: hidden
            name: baseURL
            label: Base URL
            required: false
            hint: Hostname (and path) to the root
          - widget: object
            name: params
            label: Params
            required: true
            hint: Site parameters
            fields:
              - widget: select
                name: layout_style
                label: Layout Style
                required: false
                default: default
                hint: The style of the theme layout.
                options:
                  - default
                  - overflow
              - widget: select
                name: palette
                label: Color Palette
                required: false
                default: green
                hint: The color palette of the theme.
                options:
                  - green
                  - blue
                  - violet
                  - orange
              - widget: object
                name: header
                label: Header Configuration
                required: false
                fields:
                  - widget: string
                    name: title
                    label: Header Title
                    required: false
                    hint: >-
                      The title displayed on the left side. If value is not set,
                      the author name will be used.
                  - widget: string
                    name: tagline
                    label: Header Tagline
                    required: false
                    hint: The tagline displayed on the left side.
                  - widget: image
                    name: profile_img
                    label: Profile Image
                    required: false
                    hint: >-
                      The author profile image displayed on the left side. If
                      value is not set, the author avatar will be used.
                  - widget: select
                    name: bg
                    label: Header Background
                    required: false
                    default: light
                    hint: The background of the left side.
                    options:
                      - light
                      - dark
                  - widget: boolean
                    name: has_nav
                    label: Enable Navigation Menu
                    required: false
                    default: true
                    hint: Display the navigation menu bar on the left side.
                  - widget: boolean
                    name: has_social
                    label: Enable Social Links
                    required: false
                    default: true
                    hint: Display social links on the left side.
              - widget: object
                name: footer
                label: Footer Configuration
                required: false
                fields:
                  - widget: string
                    name: content
                    label: Footer Content
                    required: false
                    hint: The copyright text displayed in the footer.
                  - widget: list
                    name: links
                    label: Links
                    required: false
                    hint: A list of links displayed in the footer.
                    fields:
                      - widget: string
                        name: text
                        label: Link text
                        required: false
                      - widget: string
                        name: url
                        label: URL
                        required: false
                      - widget: boolean
                        name: new_window
                        label: Open in new window
                        required: false
                        default: true
          - widget: object
            name: menu
            label: Site Menus
            required: false
            hint: Menu items not related to a specific page
            fields:
              - widget: list
                name: main
                label: Main menu
                required: false
                hint: List of items for Main menu
                fields:
                  - widget: string
                    name: identifier
                    label: Identifier
                    required: true
                    hint: >-
                      The identifier of a menu item could be used as a parent
                      menu of another menu item
                  - widget: string
                    name: name
                    label: Title
                    required: true
                    hint: The title of the menu item
                  - widget: string
                    name: url
                    label: URL
                    required: true
                    hint: The URL the menu item links to
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
                  - widget: string
                    name: parent
                    label: Parent Menu Identifier
                    required: false
                    hint: >-
                      The parent of an entry should be the identifier of another
                      entry.
          - widget: hidden
            name: disableKinds
            label: Disable Kinds
            required: false
            hint: Enable disabling of all pages of the specified Kinds.
          - widget: hidden
            name: uglyURLs
            label: Ugly URLs
            required: false
            hint: >-
              When enabled, creates URL of the form /filename.html instead of
              /filename/.
  - name: social
    label: Social Links
    files:
      - name: social
        label: Social Links
        file: config.yaml
        fields:
          - widget: object
            name: params
            label: Social Links
            required: false
            hint: A list of social links displayed on the left side.
            fields:
              - widget: list
                name: social
                label: Social Links
                required: false
                fields:
                  - widget: string
                    require: true
                    name: icon
                    label: Icon
                    hint: Fontawesome icon
                  - widget: string
                    name: url
                    require: true
                    label: Url
                  - widget: number
                    name: weight
                    label: Weight
                    require: true
                    valueType: int
  - name: contact
    label: Contact
    files: 
      - name: contact
        file: config.yaml
        label: Contact 
        fields:
          - widget: object
            name: params
            label: Contact Params        
            fields:
              - widget: object
                name: address
                label: Contact information
                required: true
                fields:
                  - widget: object
                    name: contact
                    required: true
                    fields:
                      - widget: string
                        name: phone
                        required: true
                      - widget: string
                        name: email
                        required: true
                  - widget: string
                    name: openingHours
                    required: true          
  - name: blog
    label: Blog
    create: true
    extension: md
    folder: content/blog
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the blog.
      - widget: string
        name: description
        label: Description
        required: true
        hint: The description of the blog.
      - label: "Featured Image"
        name: "featureImage"
        widget: "image"     
        required: true
        media_folder: "/static/images/allpost"
        media_library:
          config:
            multiple: false
      - label: "Post Image"
        name: "postImage"
        widget: "image"     
        required: false
        media_folder: "/static/images/blog"
        media_library:
          config:
            multiple: false
      - label: "Manual Update Files"
        name: "updateFiles"
        required: false
        widget: "file"
        media_library:
          config:
            multiple: true
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
        date_format: true
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        add_to_top: true
      - widget: boolean
        name: draft
        label: Draft
        required: false
        default: true     
      - widget: markdown
        name: body
        label: Content
        required: true
        hint: Page content
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: blog
  - name: post
    label: Posts
    folder: content/posts
    create: true
    extension: md
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the post
      - widget: string
        name: subtitle
        label: Subtitle
        required: false
        hint: The text shown just below the post title.
      - widget: date
        name: date
        label: Date
        required: true
      - widget: image
        name: thumb_img_path
        label: Featured Image
        required: false
        hint: The image shown in the blog feed.
      - widget: image
        name: content_img_path
        label: Alternative Featured Image
        required: false
        hint: The image shown in the single post.
      - widget: string
        name: excerpt
        label: Excerpt
        required: false
        hint: The excerpt of the post displayed in the blog feed.
      - widget: image
        name: canonical_url
        label: Canonical URL
        required: false
        hint: 'The canonical url of the post, if post originates elsewhere.'
      - widget: object
        name: menu
        label: Post Menus
        required: false
        hint: Which menus should this page show up in
        fields:
          - widget: object
            name: main
            label: Main menu item
            required: false
            hint: Main menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: post
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: layout
      value: post
